### ISSUE TITLE
Search to other apps not only browser

### ISSUE THREAD

**Issue by rdrd00** [Rudloff/search-to-browser#2]
If I want to search with Pixel Search app or Sesame Search & Shortcuts app instead of browsers then there is no option for that. so i am requesting the developer to implement this feature. and please reply if it is possible or not. if you implement this feature then this app will be more amazing.

**Comment by rdrd00** [comment]
i accidentaly closed this issue

**Comment by Rudloff** [comment]
Duplicate of #3

**Comment by rdrd00** [comment]
> Duplicate of #3

sorry i accidentally closed the issue then opened new issue.

**Comment by rdrd00** [comment]
> Duplicate of #3

i really disappointed after reading this "rudolff closed this as not planned" 
please i am begging for it 2nd time. don't say like that it's not planned, please try to implement this feature because you are the developer we can demand to you only. everybody will like it, please! 
purpose of your app was making that searchbox useful so i want it to be more useful.
you can release this app as paid app on playstore i and everyone can happily pay for it.

**Comment by Rudloff** [comment]
#3 is still open, I only closed the duplicate (#2).

**Comment by rdrd00** [comment]
> #3 is still open, I only closed the duplicate (#2).

thank god! you will work on this 😊
i got afraid by reading "closed as not planned"
love you bro 😘
